### ISSUE TITLE
issue on v1.39.1

### ISSUE THREAD

**Issue by Apollyon8888** [kindawindytoday/Minty-Releases#10]
''No Sprint CD'' not working on latest V1.39.1
- gliding and climbing not working
- auto talk / fast talk seems not working too

**Comment by BreadtheRipper** [comment]
Sprinting is also completely broken, even the icon disappears, and character can't sprint at all
Attempting to open the team edit screen with instant team open enabled instantly crashing game

**Comment by Apollyon8888** [comment]
mine the icon is visible just nothing happen when press it. im using controller. cant glide, sprint and climb even when turn off all the features problem still persist.... perhaps can just use back the older program but with updates.
