### ISSUE TITLE
Does it support cn server？

### ISSUE THREAD

**Issue by TokikiriNanaya** [kindawindytoday/Minty-Releases#3]
It crashed when I used it to open the cn server

`__main__ Exception'gbk' codec can't decode byte 0xa1 in position 90: illegal multibyte sequenceTraceback (most recent call last):
  File "upload_crash.py", line 86, in <module>
  File "upload_crash.py", line 53, in upload_crash
  File "upload_crash.py", line 24, in get_info
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 90: illegal multibyte sequence`

**Comment by EtoShinya** [comment]
CN version is not supported.
