### ISSUE TITLE
When it reached the point of loading fonts, the game crashed

### ISSUE THREAD

**Issue by icefishsss** [kindawindytoday/Minty-Releases#4]
When it reached the point of loading fonts, the game crashed，and it's china game client

**Comment by icefishsss** [comment]
how can i solve it

**Comment by icefishsss** [comment]
its version is .1.38 and 1.37 also don't work
Genshin version is the latest version ,i don't know how to solve it
hope you can help me solve it

**Comment by EtoShinya** [comment]
> its version is .1.38 and 1.37 also don't work Genshin version is the latest version ,i don't know how to solve it hope you can help me solve it

No antiviruses and overlays are enabled? Can you show the full log in the console?
